dictionary/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("mainapp.urls")),
    path('admin/', admin.site.urls),
]

mainapp/urls.py
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
# from django.contrib.auth.views import LoginView
from django.urls import path, re_path, include
from .views import RegisterView, CustomLoginView, ResetPasswordView, ChangePasswordView
from .forms import LoginForm
# from django.conf import settings
# from django.conf.urls.static import static

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("search/", views.search, name="search"),
    path("contact/", views.contact, name="contact"),
    # path('login/', LoginView.as_view(redirect_authenticated_user=True), name='login'),
    # path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    # path('register/', views.register, name='register'),
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', CustomLoginView.as_view(redirect_authenticated_user=True, template_name='registration/login.html',
                                           authentication_form=LoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='registration/logout.html'), name='logout'),
    path('accounts/profile/', views.profile, name='profile'),
    re_path(r'^oauth/', include('social_django.urls', namespace='social')),
    path('password-reset/', ResetPasswordView.as_view(), name='password_reset'),
    path('password-reset-confirm/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
        name='password_reset_confirm'),
    path('password-reset-complete/',
        auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
        name='password_reset_complete'),
    path('password-change/', ChangePasswordView.as_view(), name='password_change'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/models.py
from django.contrib.auth.models import User
from django.db import models
from PIL import Image

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    account_name = models.CharField(max_length=50, default='default_account')
    location  = models.CharField(max_length=100, blank=True, null=True)
    bio = models.TextField(blank=True)
    avatar = models.ImageField(upload_to='avatars', default='default_avatar.png')
    created_at = models.DateTimeField(auto_now_add=True)
    last_updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.username
        
    # resizing images
    def save(self, *args, **kwargs):
        super().save()

        img = Image.open(self.avatar.path)

        if img.height > 100 or img.width > 100:
            new_img = (100, 100)
            img.thumbnail(new_img)
            img.save(self.avatar.path)

mainapp/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .models import Profile
 
class IDict(forms.Form):
    sentence = forms.CharField()
    word = forms.CharField()
    response_language = forms.CharField()
    CHOICES = (('1', 1),('2', 2),('3', 3),('4', 4),('5', 5),)
    number_of_meanings = forms.ChoiceField(choices=CHOICES)

# class UserProfileForm(forms.ModelForm):
#     class Meta:
#         model = Profile
#         fields = ['bio', 'avatar']

class RegisterForm(UserCreationForm):
    # fields we want to include and customize in our form
    first_name = forms.CharField(max_length=100,
                                 required=True,
                                 widget=forms.TextInput(attrs={'placeholder': 'First Name',
                                                               'class': 'form-control',
                                                               }))
    last_name = forms.CharField(max_length=100,
                                required=True,
                                widget=forms.TextInput(attrs={'placeholder': 'Last Name',
                                                              'class': 'form-control',
                                                              }))
    username = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput(attrs={'placeholder': 'Username',
                                                             'class': 'form-control',
                                                             }))
    email = forms.EmailField(required=True,
                             widget=forms.TextInput(attrs={'placeholder': 'Email',
                                                           'class': 'form-control',
                                                           }))
    password1 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput(attrs={'placeholder': 'Password',
                                                                  'class': 'form-control',
                                                                  'data-toggle': 'password',
                                                                  'id': 'password',
                                                                  }))
    password2 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput(attrs={'placeholder': 'Confirm Password',
                                                                  'class': 'form-control',
                                                                  'data-toggle': 'password',
                                                                  'id': 'password',
                                                                  }))

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', 'password1', 'password2']

class LoginForm(AuthenticationForm):
    username = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput(attrs={'placeholder': 'Username',
                                                             'class': 'form-control',
                                                             }))
    password = forms.CharField(max_length=50,
                               required=True,
                               widget=forms.PasswordInput(attrs={'placeholder': 'Password',
                                                                 'class': 'form-control',
                                                                 'data-toggle': 'password',
                                                                 'id': 'password',
                                                                 'name': 'password',
                                                                 }))
    remember_me = forms.BooleanField(required=False)

    class Meta:
        model = User
        fields = ['username', 'password', 'remember_me']

class UpdateUserForm(forms.ModelForm):
    username = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(required=True,
                             widget=forms.TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ['username', 'email']


class UpdateProfileForm(forms.ModelForm):
    avatar = forms.ImageField(widget=forms.FileInput(attrs={'class': 'form-control-file'}))
    bio = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 5}))

    class Meta:
        model = Profile
        fields = ['avatar', 'bio']

mainapp/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.views import LoginView, PasswordResetView, PasswordChangeView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.messages.views import SuccessMessageMixin
from django.views import View
from django.urls import reverse_lazy

from .forms import IDict, Profile, RegisterForm, LoginForm, UpdateUserForm, UpdateProfileForm
import openai
import json

openai.api_key = 'J2A1SE9tq3NSlX_CpODTK2Iwcm5d2x_XK-GCKsk-nNnV7kARI5IoVFDlFxVwymdV0gsbG8TNxTkLMVmmPndv0xQ'
openai.api_base = 'https://api.openai.iniad.org/api/v1'


def get_completion(prompt, model="gpt-3.5-turbo",temperature=0):
    messages = [{"role": "user", "content": prompt}]
    response = openai.ChatCompletion.create(
        model=model,
        messages=messages,
        temperature=temperature, # this is the degree of randomness of the model's output
    )
    return response.choices[0].message["content"]
def get_response(sentence, word, number_of_meanings=1, response_language="English"):
    prompt = f"""
        You are an intelligent dictionary.
        Given a sentence and a word in that sentence, you need to:

        1. Identify the language of the sentence.
        2. Provide {number_of_meanings} closest meanings in {response_language} to the meaning of the word in the sentence, along with their similarity scores.
        Include sample sentences in the identified language and their corresponding meanings in {response_language}.
        Ensure that the returned meanings are in {response_language}, and limit the sample sentences to a maximum of 10 words.

        3. Sort the meanings in descending order based on the similarity score.
        4. Format your response in JSON as follows:

        {{
            "Language": "",
            "Meanings": [
                {{
                    "meaning": "",
                    "similarity_score": "",
                    "example_sentence": "",
                    "example_sentence_meaning": ""
                }},
                ...
            ]
        }}
        
        The sentence is enclosed within triple backticks, and the word is enclosed within triple backticks.
        Sentence: ```{sentence}```
        Word: ```{word}```
    """

    response = get_completion(prompt, temperature=0.1)
    # print(response)
    return json.loads(response)

def search(request):
    if request.method == 'POST':
        form = IDict(request.POST)
        # print(form)
        if form.is_valid():
            # Process the form data
            # Access the form fields using form.cleaned_data dictionary
            sentence = form.cleaned_data['sentence']
            word = form.cleaned_data['word']
            response_language = form.cleaned_data['response_language']
            number_of_meanings = form.cleaned_data['number_of_meanings']
            
            # print(word, sentence, number_of_meanings, response_language)
            
            response = get_response(sentence, word, number_of_meanings, response_language)
            meanings = response['Meanings'][:int(number_of_meanings)]
            # print(response, type(response))
            # Redirect to a success page or do further processing
            return render(request, 'search.html', {'form': form, 'response': response, 'meanings': meanings})
        else:
            print(form.errors.as_data())
    else:
        form = IDict()
    return render(request, 'search.html', {'form': form})

def index(request):
    return render(request, 'home.html')

def contact(request):
    return render(request, 'contact.html')

def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        print (form)
        if form.is_valid():
            user = form.save()
            # Create UserProfile for the newly registered user
            Profile.objects.create(user=user)
            # Log the user in
            login(request, user)
            return redirect('login')  # Redirect to the homepage or any other desired page
    else:
        form = UserCreationForm()
    return render(request, 'registration/register.html', {'form': form})

@login_required
def profile(request):
    if request.method == 'POST':
        user_form = UpdateUserForm(request.POST, instance=request.user)
        profile_form = UpdateProfileForm(request.POST, request.FILES, instance=request.user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Your profile is updated successfully')
            return redirect(to='profile')
    else:
        user_form = UpdateUserForm(instance=request.user)
        profile_form = UpdateProfileForm(instance=request.user.profile)
    return render(request, 'profile.html', {'user_form': user_form, 'profile_form': profile_form})

# @login_required
# def custom_login(request, *args, **kwargs):
#     # If user is already authenticated, redirect to their profile
#     print(1231231)
#     if request.user.is_authenticated:
#         return redirect('profile')

#     # If user is not authenticated, continue with the regular login view
#     return auth_login(request, *args, **kwargs)

class RegisterView(View):
    form_class = RegisterForm
    initial = {'key': 'value'}
    template_name = 'registration/register.html'

    def dispatch(self, request, *args, **kwargs):
        # will redirect to the home page if a user tries to access the register page while logged in
        if request.user.is_authenticated:
            return redirect(to='/')

        # else process dispatch as it otherwise normally would
        return super(RegisterView, self).dispatch(request, *args, **kwargs)
    def get(self, request, *args, **kwargs):
        form = self.form_class(initial=self.initial)
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)

        if form.is_valid():
            form.save()

            username = form.cleaned_data.get('username')
            messages.success(request, f'Account created for {username}')

            return redirect(to='login')

        return render(request, self.template_name, {'form': form})
    
class CustomLoginView(LoginView):
    form_class = LoginForm

    def form_valid(self, form):
        remember_me = form.cleaned_data.get('remember_me')

        if not remember_me:
            # set session expiry to 0 seconds. So it will automatically close the session after the browser is closed.
            self.request.session.set_expiry(0)

            # Set session as modified to force data updates/cookie to be saved.
            self.request.session.modified = True

        # else browser session will be as long as the session cookie time "SESSION_COOKIE_AGE" defined in settings.py
        return super(CustomLoginView, self).form_valid(form)
    
class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = 'registration/password_reset.html'
    email_template_name = 'registration/password_reset_email.html'
    subject_template_name = 'registration/password_reset_subject'
    success_message = "We've emailed you instructions for setting your password, " \
                      "if an account exists with the email you entered. You should receive them shortly." \
                      " If you don't receive an email, " \
                      "please make sure you've entered the address you registered with, and check your spam folder."
    success_url = reverse_lazy('login')

class ChangePasswordView(SuccessMessageMixin, PasswordChangeView):
    template_name = 'registration/change_password.html'
    success_message = "Successfully Changed Your Password"
    success_url = reverse_lazy('profile')

mainapp/templates/contact.html
{% extends 'template.html' %}
{% load static %}
{% block content %}
  <div class="container  mt-4">
      <h1>Get in touch</h1>
      <p>Feel free to get in touch with us through any of the following channels:</p>
        <ul>
            <li><i class="fa-solid fa-envelope"></i> Email: <a href="ms1f102010018@iniad.org">s1f102010018@iniad.org</a></li>
            <li><i class="fa fa-linkedin"></i> LinkedIn: <a href="https://www.linkedin.com/in/anh-bui-7a7470196/">Anh Bui</a></li>
            <li><i class="fa fa-phone"></i> Phone: <a href="https://www.linkedin.com/in/anh-bui-7a7470196/">090 090 090</a></li>
        </ul>
    </div>  
{% endblock content %}

mainapp/templates/home.html
{% extends 'template.html' %}
{% load static %}
{% block title %} Intelligent Dictionary {% endblock title%}
{% block content %}
  <header>
    <div class="header_big my-4 p-4">
      <img src="{% static 'img/logo.png' %}" class="mb-4" alt="Logo" style="border-radius: 50%;">
      <h1>The intelligent dictionary you need</h1>
      <span class="span_header">Welcome to our revolutionary web application designed to make word searches faster and more efficient! Say goodbye to the traditional way of sifting through numerous definitions to find the perfect match for your word's meaning. With our cutting-edge platform, all you need to do is input the keyword and provide a context sentence, and we'll do the rest for you. Our advanced algorithm will analyze the context and present you with the closest meanings to your word, saving you valuable time and effort. Embrace the future of word exploration and experience the convenience of our intelligent word search tool. Say hello to <b>quick, accurate</b> word meanings at your fingertips!</span> <br>
      
      <button><a href="{% url 'search' %}">Get Started</a></button>
    </div>
  </header>  
{% endblock content %}   

mainapp/templates/profile.html
{% extends 'template.html' %}
{% block title %} Intelligent Dictionary | Profile Page {% endblock title %}
{% block content %}
<div class="container my-4">
  <div class="my-3 p-3">
    <img class="rounded-circle account-img mb-4" src="{{ user.profile.avatar.url }} " style="cursor: pointer;"/>
    <div class="form-group rmb-me">
        <label class="mb-1">Change Avatar:</label>
        {{ profile_form.avatar }} 
    </div>

  </div>
{% if user_form.errors %}
    <div class="alert alert-danger alert-dismissible" role="alert">
        <div id="form_errors">
            {% for key, value in user_form.errors.items %}
                <strong>{{ value }}</strong>
            {% endfor %}
        </div>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
{% endif %}
<div class="form-content">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-row">
            <div class="col-md-12">
                <div class="form-group">
                    <label class="mb-1">Username:</label>
                        {{ user_form.username }}
                    <label class="mb-1">Email:</label>
                        {{ user_form.email }}
                </div>
                <div class="form-group">
                    <label class="mb-1">Bio:</label> {{ profile_form.bio }}   
                </div>                          
                <div class="form-row justify-content-center">
                    <a href="{% url 'password_change' %}">Change Password</a>          
                </div>
            </div>
        </div>
        <br><br>
        <button type="submit" class="btn btn-dark btn-lg">Save Changes</button>
        <button type="reset" class="btn btn-dark btn-lg">Reset</button>
    </form>
</div>
</div>
{% endblock %}

mainapp/templates/search.html
{% extends 'template.html' %}
{% load static %}
{% block content %}
      <div class="container my-4">
        
        <form method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="form-group">
            <label for="id_word"><i class="fa-solid fa-underline"></i></label>
            <input type="text" name="word" class="form-control" required id="id_word" placeholder="Key word in the sentence">
          </div>
          <div class="form-group">
            <label for="id_sentence"><i class="fa-regular fa-pen-to-square"></i></label>
            <input type="text" name="sentence" class="form-control" required id="id_sentence" placeholder="Your context sentence">
          </div>

            <div class="form-group">
                <label for="id_response_language"><i class="fa-solid fa-language"></i></label>
                <select type="text" name="response_language" class="form-control" required id="id_response_language">
                  <option selected disabled>Response Language</option>
                  <option value="AB">Abkhazian</option>
                  <option value="AA">Afar</option>
                  <option value="AF">Afrikanns</option>
                  <option value="SQ">Albanian</option>
                  <option value="AM">Amharic</option>
                  <option value="AR">Arabic</option>
                  <option value="HY">Armenian</option>
                  <option value="AS">Assamese</option>
                  <option value="AY">Aymara</option>
                  <option value="AZ">Azerbaijani</option>
                  <option value="BA">Bashkir</option>
                  <option value="EU">Basque</option>
                  <option value="BN">Bengali, Bangla</option>
                  <option value="DZ">Bhutani</option>
                  <option value="BH">Bihari</option>
                  <option value="BI">Bislama</option>
                  <option value="BR">Breton</option>
                  <option value="BG">Bulgarian</option>
                  <option value="MY">Burmese</option>
                  <option value="BE">Byelorussian</option>
                  <option value="KM">Cambodian</option>
                  <option value="CA">Catalan</option>
                  <option value="ZH">Chinese (Mandarin)</option>
                  <option value="CO">Corsican</option>
                  <option value="HR">Croation</option>
                  <option value="CS">Czech</option>
                  <option value="DA">Danish</option>
                  <option value="NL">Dutch</option>
                  <option value="EN">English, American</option>
                  <option value="EO">Esperanto</option>
                  <option value="ET">Estonian</option>
                  <option value="FO">Faeroese</option>
                  <option value="FJ">Fiji</option>
                  <option value="FI">Finnish</option>
                  <option value="FR">French</option>
                  <option value="FY">Frisian</option>
                  <option value="GD">Gaelic (Scots Gaelic)</option>
                  <option value="GL">Galician</option>
                  <option value="KA">Georgian</option>
                  <option value="DE">German</option>
                  <option value="EL">Greek</option>
                  <option value="KL">Greenlandic</option>
                  <option value="GN">Guarani</option>
                  <option value="GU">Gujarati</option>
                  <option value="HA">Hausa</option>
                  <option value="IW">Hebrew</option>
                  <option value="HI">Hindi</option>
                  <option value="HU">Hungarian</option>
                  <option value="IS">Icelandic</option>
                  <option value="IN">Indonesian</option>
                  <option value="IA">Interlingua</option>
                  <option value="IE">Interlingue</option>
                  <option value="IK">Inupiak</option> 
                  <option value="GA">Irish</option>
                  <option value="IT">Italian</option>
                  <option value="JA">Japanese</option>
                  <option value="JW">Javanese</option>
                  <option value="KN">Kannada</option>
                  <option value="KS">Kashmiri</option>
                  <option value="KK">Kazakh</option>
                  <option value="RW">Kinyarwanda</option>
                  <option value="KY">Kirghiz</option>
                  <option value="RN">Kirundi</option>
                  <option value="KO">Korean</option>
                  <option value="KU">Kurdish</option>
                  <option value="LO">Laothian</option>
                  <option value="LA">Latin</option>
                  <option value="LV">Latvian, Lettish</option>
                  <option value="LN">Lingala</option>
                  <option value="LT">Lithuanian</option>
                  <option value="MK">Macedonian</option>
                  <option value="MG">Malagasy</option>
                  <option value="MS">Malay</option>
                  <option value="ML">Malayalam</option>
                  <option value="MT">Maltese</option>
                  <option value="MI">Maori</option>
                  <option value="MR">Marathi</option>
                  <option value="MO">Moldavian</option>
                  <option value="MN">Mongolian</option>
                  <option value="NA">Nauru</option>
                  <option value="NE">Nepali</option>
                  <option value="NO">Norwegian</option>
                  <option value="OC">Occitan</option>
                  <option value="OR">Oriya</option>
                  <option value="OM">Oromo, Afan</option>
                  <option value="PS">Pashto, Pushto</option>
                  <option value="FA">Persian</option>
                  <option value="PL">Polish</option>
                  <option value="PT">Portuguese</option>
                  <option value="PA">Punjabi</option>
                  <option value="QU">Quechua</option>
                  <option value="RM">Rhaeto-Romance</option>
                  <option value="RO">Romanian</option>
                  <option value="RU">Russian</option>
                  <option value="SM">Samoan</option>
                  <option value="SG">Sangro</option>
                  <option value="SA">Sanskrit</option>
                  <option value="SR">Serbian</option>
                  <option value="SH">Serbo-Croatian</option>
                  <option value="ST">Sesotho</option>
                  <option value="TN">Setswana</option>
                  <option value="SN">Shona</option>
                  <option value="SD">Sindhi</option>
                  <option value="SI">Singhalese</option>
                  <option value="SS">Siswati</option>
                  <option value="SK">Slovak</option>
                  <option value="SL">Slovenian</option>
                  <option value="SO">Somali</option>
                  <option value="ES">Spanish</option>
                  <option value="SU">Sudanese</option>
                  <option value="SW">Swahili</option>
                  <option value="SV">Swedish</option>
                  <option value="TL">Tagalog</option>
                  <option value="TG">Tajik</option>
                  <option value="TA">Tamil</option>
                  <option value="TT">Tatar</option>
                  <option value="TE">Telugu</option>
                  <option value="TH">Thai</option>
                  <option value="BO">Tibetan</option>
                  <option value="TI">Tigrinya</option>
                  <option value="TO">Tonga</option>
                  <option value="TS">Tsonga</option>
                  <option value="TR">Turkish</option>
                  <option value="TK">Turkmen</option>
                  <option value="TW">Twi</option>
                  <option value="UK">Ukranian</option>
                  <option value="UR">Urdu</option>
                  <option value="UZ">Uzbek</option>
                  <option value="VI">Vietnamese</option>
                  <option value="VO">Volapuk</option>
                  <option value="CY">Welsh</option>
                  <option value="WO">Wolof</option>
                  <option value="XH">Xhosa</option>
                  <option value="JI">Yiddish</option>
                  <option value="YO">Yoruba</option>
                  <option value="ZU">Zulu</option>
                </select>
            </div>
            <div class="form-group">
                <label for="id_number_of_meanings"><i class="fa-solid fa-list-ul"></i></label>
                <select class="form-control" name="number_of_meanings" id="id_number_of_meanings">
                    <option selected disabled>Number of meanings</option>
                    <option value="1">1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                    <option value="5">5</option>
                </select>
            </div>
          

          <button type="submit" class="btn btn-primary"><i class="fa-solid fa-magnifying-glass"></i>Search</button>
        </form>
      
      
        {% if response %}
          <h1>Language: {{response.Language}}</h1>
          <table>
            <tr>
              <th>Meaning</th>
              <th>Similarity score</th>
              <th>Example</th>
              <th>Example meaning</th>
            </tr>
            {% for m in meanings %}
              <tr>
                <td>{{m.meaning}}</td> 
                <td>{{m.similarity_score}}</td> 
                <td>{{m.example_sentence}}</td>
                <td>{{m.example_sentence_meaning}}</td>
              </tr>
            {% endfor %}
          </table>
        {% endif %}
      </div>
      {% endblock content %}